### ISSUE TITLE
YanModTeleporter not workds with last build HF

### ISSUE THREAD

**Issue by dEROZA** [HorridoJoho/YANModPack#1]
1. ERROR in \YANModPack\YANTeleporter\YANTeleporter.java (at line 135)
       if (!member.isInsideRadius(npc.getX(), npc.getY(), teleLoc.maxMemberDistance, true))
                   ^^^^^^^^^^^^^^
   The method isInsideRadius(ILocational, int, boolean, boolean) in the type L2Character is not applicable for the arguments (int, int, int, boolean)
   ----------
2. ERROR in \YANModPack\YANTeleporter\YANTeleporter.java (at line 158)
       member.teleToLocation(teleLoc.pos.x, teleLoc.pos.y, teleLoc.pos.z);
                             ^^^^^^^^^^^
   L2CharPosition cannot be resolved to a type
   ----------
3. ERROR in \YANModPack\YANTeleporter\YANTeleporter.java (at line 158)
       member.teleToLocation(teleLoc.pos.x, teleLoc.pos.y, teleLoc.pos.z);
                                            ^^^^^^^^^^^
   L2CharPosition cannot be resolved to a type
   ----------
4. ERROR in \YANModPack\YANTeleporter\YANTeleporter.java (at line 158)
       member.teleToLocation(teleLoc.pos.x, teleLoc.pos.y, teleLoc.pos.z);
                                                           ^^^^^^^^^^^
   L2CharPosition cannot be resolved to a type
   ----------
   ----------
5. ERROR in C:\Users\Avtom\Downloads\Fun\Backup\L2JServer\game\data\scripts\YANModPack\YANTeleporter\YANTeleporterData.java (at line 33)
       import com.l2jserver.gameserver.datatables.NpcTable;
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   The import com.l2jserver.gameserver.datatables.NpcTable cannot be resolved
   ----------
6. ERROR in C:\Users\Avtom\Downloads\Fun\Backup\L2JServer\game\data\scripts\YANModPack\YANTeleporter\YANTeleporterData.java (at line 34)
       import com.l2jserver.gameserver.model.L2CharPosition;
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   The import com.l2jserver.gameserver.model.L2CharPosition cannot be resolved
   ----------
7. ERROR in C:\Users\Avtom\Downloads\Fun\Backup\L2JServer\game\data\scripts\YANModPack\YANTeleporter\YANTeleporterData.java (at line 53)
       protected final L2CharPosition pos;
                       ^^^^^^^^^^^^^^
   L2CharPosition cannot be resolved to a type
   ----------
8. ERROR in C:\Users\Avtom\Downloads\Fun\Backup\L2JServer\game\data\scripts\YANModPack\YANTeleporter\YANTeleporterData.java (at line 58)
       protected TeleportLocation(String ident, String name, int minMembers, int maxMemberDistance, L2CharPosition pos, Element elem)
                                                                                                    ^^^^^^^^^^^^^^
   L2CharPosition cannot be resolved to a type
   ----------
9. ERROR in C:\Users\Avtom\Downloads\Fun\Backup\L2JServer\game\data\scripts\YANModPack\YANTeleporter\YANTeleporterData.java (at line 64)
       this.pos = pos;
       ^^^^^^^^
   L2CharPosition cannot be resolved to a type
   ----------
10. ERROR in C:\Users\Avtom\Downloads\Fun\Backup\L2JServer\game\data\scripts\YANModPack\YANTeleporter\YANTeleporterData.java (at line 237)
        _teleLocs.put(ident, new TeleportLocation(ident, name, minMembers, maxMemberDistance, new L2CharPosition(x, y, z, 0), curElem));
                                                                                                  ^^^^^^^^^^^^^^
    L2CharPosition cannot be resolved to a type
    ----------
11. ERROR in C:\Users\Avtom\Downloads\Fun\Backup\L2JServer\game\data\scripts\YANModPack\YANTeleporter\YANTeleporterData.java (at line 255)
        L2NpcTemplate npc = NpcTable.getInstance().getTemplate(id);
                            ^^^^^^^^
    NpcTable cannot be resolved

**Comment by HorridoJoho** [comment]
A rewrite of YANTeleporter is on it's way.
1. It will use JAXB
2. It will support solo, party and command channel teleports
3. It supports creating an instance and teleport into that instance(for all three teleport types)

**Comment by dEROZA** [comment]
Thanks very very very )))))))))))))))) You best!

**Comment by HorridoJoho** [comment]
It should be resolved, the rework is finished and merged with master.
